server {
    listen 80 default_server;
    root /app/public;

    server_name _;

    location = /insights {
        return 302 https://gamma.app/docs/Vy-Fan-Engagement-Insights-for-MLB-ubkvqeajphz4cg4?mode=doc;
    }

    location ~* ^/(api|user|home|dashboard|locations|schedule|settings|report|profile|playlist|admin|chat|docs|bluesky|billing|uploads) {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:3000; #port where you are serving your express app.
    }
}